# 数据库双写切换配置
dbswitch:
  # 是否启用
  enabled: true
  # 消息队列类型：如果不指定，会根据依赖自动选择
  # mq:
  #   type: ROCKET_MQ
  # RocketMQ配置
  rocketmq:
    topic: dbswitch-topic
    consumer-group: dbswitch-consumer-group
  # RabbitMQ配置
  rabbitmq:
    exchange: dbswitch-exchange
    queue: dbswitch-queue
    routingKey: dbswitch-routingkey
    delayExchange: dbswitch-delay-exchange
    delayQueue: dbswitch-delay-queue
    delayRoutingKey: dbswitch-delay-routingkey
  # 幂等性配置
  idempotent:
    key-prefix:
      dbswitch:idempotent:
    expire-hours: 24
  # 写入模式配置
  write-mode:
    redis-key: dbswitch:write-mode
    default: MASTER_ONLY  # 默认写入模式：MASTER_ONLY、MASTER_SLAVE、SLAVE_MASTER、SLAVE_ONLY

# Spring配置
spring:
  # 数据源配置
  datasource:
    # 主数据源
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://42.194.148.166:3306/db_master?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: yueyun
    # 从数据源
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://42.194.148.166:3306/db_slave?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: yueyun

  # RocketMQ配置 (仅在使用RocketMQ时需要)
  rocketmq:
    name-server: 42.194.148.166:9876
    producer:
      group: dbswitch-producer-group
  # RabbitMQ配置 (仅在使用RabbitMQ时需要)
  rabbitmq:
    host: 42.194.148.166
    port: 5672
    username: guest
    password: guest
  # Redis配置
  data:
    redis:
      host: 42.194.148.166
      timeout: 5000
      database: 0
      port: 6379